#!/bin/bash
# Suspend standard reports processing
# Makimum of 15min waiting after which gives in.
echo "Suspending standard reports processing"
curl -s -X POST "http://localhost:8080/sr-manager/system/suspend"
for COUNT in $(seq 180)
do
    STATE=$( curl -s http://localhost:8080/sr-manager/system/status )
    echo "SR state is: $STATE"
    if [[ $STATE == Suspended ]]; then
        exit 0
    fi
    sleep 5
done
echo "Warning: SR suspension failed, aborting suspend"
exit 1
