#!/bin/bash
# Suspend standard reports processing
# Makimum of 15min waiting after which gives in.
set -e

echo "Suspending standard reports processing"
RESPONSE=$( curl -s -X POST "http://localhost:8080/sr-manager/system/suspend" )
if [[ $RESPONSE != Suspending ]]; then 
    echo "Failed: unexpected response from sr-manager $RESPONSE"
    exit 1
fi
for COUNT in $(seq 180)
do
    STATE=$( curl -s http://localhost:8080/sr-manager/system/status )
    echo "SR state is: $STATE"
    if [[ $STATE == Suspended ]]; then
        exit 0
    fi
    sleep 5
done
echo "Warning: SR suspension failed, aborting suspend"
